### ISSUE TITLE
Cannot reproduce Figure 8.9

### ISSUE THREAD

**Issue by MatusGasparik** [jcdaniel91/data-science-python-dask#1]
Following the steps described in the Section 8.2 "Plotting location data as interactive heatmap", I cannot reproduce the figure 8.9. 

These are the results in the book:

Figure 8.8:
![image](https://user-images.githubusercontent.com/15058994/89706038-9949e280-d962-11ea-87d6-aa0d952f471a.png)

Figure 8.9 (after zooming in):
![image](https://user-images.githubusercontent.com/15058994/89706054-b979a180-d962-11ea-855b-f30851bd9bc2.png)

These are my results running the code in JupyterLab on a macOS:

Figure 8.8:
![image](https://user-images.githubusercontent.com/15058994/89706118-15dcc100-d963-11ea-8a87-dd42354aa0d9.png)

Figure 8.9:
![image](https://user-images.githubusercontent.com/15058994/89706124-20975600-d963-11ea-8817-d04bf1e2fed8.png)

Any ideas why is that?

**Comment by jcdaniel91** [comment]
Hmm, that's strange. I just tried to reproduce the issue in a new conda environment with a fresh dataset and didn't run into any issues. Have you tried restarting the kernel and rerunning the notebook? It looks like your zooming in isn't triggering a redraw of the map for some reason. I have a few questions to help troubleshoot:

Which browser + version are you using?
What Python version are you running?
What version of Dask, Datashader, Holoviews, and Geoviews are you running?
Does your browser show any Javascript errors?
Are there any errors displayed in the JupyterLab console?

Thanks!

**Comment by MatusGasparik** [comment]
Yes, the datashade part is not updating.

Here the infos:

**Browser**: 
Google Chrome (Version 84.0.4147.135 )

**Python env**:
Python 3.8.2
dask 2.22.0
datashader 0.11.0
geoviews 1.8.1
holoviews 1.13.3

**OS**:
ProductName: Mac OS X
ProductVersion: 10.14.6

I don't get any errors (Browser/JS or Jupyter console). I am running it in an environment created by **poetry**, so I start the notebook like so: `poetry run jupyter lab`

**Comment by jcdaniel91** [comment]
Hi Matus, I apologize for the delay - I've been away for a bit. I'm working on getting an environment set up to match yours to see what I can find. Hoping to have some advice or additional questions soon. Thanks for your patience!

**Comment by MatusGasparik** [comment]
Hi Jesse. I tried again in a fresh `conda` environment. The same problem persists. I don't get any errors or extra warnings (apart from the one concerning the alignment of the indexes), nor any errors in the console executing the jupyter lab server or JS errors in the browser's console.
I wonder whether this is some peculiarity of my setup or if any other macOS users experience the same issue. If you can't reproduce the error than don't waste your time on my problem and I will close this issue. I will have to look deeper into the `datashader` when I find time for it.

**Comment by MatusGasparik** [comment]
OK, I just figured out that the issue is related to the `jupyter lab`. Executing in the classical `jupyter notebook` works just fine. Here is the related issue: https://github.com/holoviz/datashader/issues/583

Anyway, I installed the `jupyterlab_pyviz` (see http://holoviz.org/installation.html) and now it works also in the `jupyter lab`.

**Comment by MatusGasparik** [comment]
Issue resolved with the installation of the `jupyterlab_pyviz` labextension for the `jupyter lab`.

**Comment by jcdaniel91** [comment]
Hi Matus, thanks for following up on this. I should have posted an update sooner - I too stood up a new environment using the version numbers you gave me and I'm also on macOS 10.14.6, and I was able to reproduce the issue. And just like you said, I too wasn't able to find any errors. I was trying to dig a bit deeper into what's going on before posting more ideas here. I'm glad you were able to get it to work! Definitely a strange issue. Thanks for your help!
